micronaut:
  server:
    port: 8080
  application:
    name: axon-framework-micronaut

axoniq:
  console:
    application-name: "Micronaut & Axon Flight Scheduler Example"
    dlq-mode: "FULL"

otel:
  register:
    global: true
  metric:
    export:
      interval: 5000                            # default value
  experimental:
    exporter:
      otlp:
        retry:
          enabled: true                         # default value
  traces:
    exporter: otlp                              # default value
    sampler: always_on                          # default value
  metrics:
    exporter: otlp                              # default value
  logs:
    exporter: otlp                              # default value
    max-attribute-length: 4095                  # default value
  exporter:
    otlp:
      endpoint: http://localhost:4317           # default value
      compression: gzip                         # default value